# Generated by Django 3.2.15 on 2022-09-14 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220913_2146'),
    ]

    operations = [
    ]
